# Hằng số icon sử dụng emoji
ICON_TRAIN = "🚀"
ICON_PREDICT = "🔍"
ICON_STOP = "⏹️"
ICON_SAVE = "💾"
ICON_LOAD = "📂"
ICON_BROWSE = "📁"
ICON_CLEAR = "🗑️"
ICON_EXPORT = "📤"
ICON_SETTINGS = "⚙️"
ICON_INFO = "ℹ️"
ICON_WARNING = "⚠️"
ICON_ERROR = "❌"
ICON_SUCCESS = "✅"
ICON_CHART = "📊"
ICON_IMAGE = "🖼️"
ICON_VIDEO = "🎥"
ICON_FOLDER = "📁"
