train: dataset/train/images
val: dataset/valid/images
test: dataset/test/images

nc: 23
names: ['Button', 'Capacitor', 'Capacitor Jumper', 'Clock', 'Connector', 'Diode', 'EM', 'Electrolytic Capacitor', 'Ferrite Bead', 'IC', 'Inductor', 'Jumper', 'Led', 'Pads', 'Pins', 'Resistor', 'Resistor Jumper', 'Resistor Network', 'Switch', 'Test Point', 'Transistor', 'Unknown Unlabeled', 'iC']

roboflow:
  workspace: roboflow-100
  project: printed-circuit-board
  version: 4
  license: CC BY 4.0
  url: https://universe.roboflow.com/roboflow-100/printed-circuit-board/dataset/4